version: '2'

networks:
  app-tier:
    driver: bridge

services:
  app:
    build:
      dockerfile: ../.environment/Dockerfile
      context: ../../Template.Api/
    ports:
      - 80:80
    depends_on: 
      - etcd
      - redis
    networks: 
      - app-tier
  redis:
    image: 'redis:5-alpine'
    networks:
      - app-tier
  etcd:
    image: quay.io/coreos/etcd:v3.1.13
    entrypoint: /usr/local/bin/etcd
    command:
        - '--name=etcd-1'
        - '--initial-advertise-peer-urls=http://etcd-1:2380'
        - '--listen-peer-urls=http://etcd-1:2380'
        - '--listen-client-urls=http://etcd-1:2379,http://localhost:2379'
        - '--advertise-client-urls=http://etcd-1:2379'
        - '--initial-cluster-token=mys3cr3ttok3n'
        - '--heartbeat-interval=250'
        - '--election-timeout=1250'
        - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
    networks:
      - app-tier