version: '3'

networks:
  app-tier:
    driver: bridge

services:
  app:
    build:
      dockerfile: ../.environment/Dockerfile
      context: ../../Template.Api/
    ports:
      - 80:80
    depends_on: 
      - etcd
      - redis
    networks: 
      - app-tier
  redis:
    image: 'redis:5-alpine'
    networks:
      - app-tier
  etcd:
    image: quay.io/coreos/etcd:v3.1.13
    entrypoint: /usr/local/bin/etcd
    command:
        - '--name=etcd'
        - '--initial-advertise-peer-urls=http://etcd:2380'
        - '--listen-peer-urls=http://etcd:2380'
        - '--listen-client-urls=http://etcd:2379,http://localhost:2379'
        - '--advertise-client-urls=http://etcd:2379'
        - '--initial-cluster-token=mys3cr3ttok3n'
        - '--heartbeat-interval=250'
        - '--election-timeout=1250'
        # - '--initial-cluster=etcd=http://etcd:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:2379/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-tier
  mongo:
    image: mongo:3
    networks:
      - app-tier
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-tier
  graylog:
    image: graylog/graylog:2.4
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
    networks:
      - app-tier